<?php

declare(strict_types=1);

/**
 * Automated setup (from project root):
 *   php scripts/setup_secrets.php "your-strong-password"
 *
 * Or copy this file to secrets.php and set password_hash manually (see scripts/hash_password.php).
 * secrets.php is gitignored — never commit it.
 */
return [
    'password_hash' => '',
    /** Optional: https://your-cdn.example.com (no trailing slash). Used for full email image URLs when set. */
    'public_base_url' => '',
    /** Optional: hex key for signed dynamic timer URLs (auto-generated by installer/setup script). */
    'timer_signing_key' => '',

    /**
     * Outbound email (`smtp` recommended in production).
     *
     * `log` writes messages to data/mail-out.log (default for local dev).
     */
    'mail_transport' => 'log',
    'smtp_host' => '',
    'smtp_port' => 587,
    /** tls (STARTTLS on 587), ssl (SMTPS on 465), or none */
    'smtp_encryption' => 'tls',
    'smtp_username' => '',
    'smtp_password' => '',
    'smtp_timeout' => 20,
    /** Must be a sender your provider authorizes (SPF/DKIM). */
    'mail_from_email' => '',
    'mail_from_name' => 'Email countdown',

    /** Sample successful timer renders to avoid noisy logs. Errors are always logged. */
    'timer_render_success_sample_rate' => 0.02,
];
