<?php

declare(strict_types=1);

/**
 * Automated setup (from project root):
 *   php scripts/setup_secrets.php "your-strong-password"
 *
 * Or copy this file to secrets.php and set password_hash manually (see scripts/hash_password.php).
 * secrets.php is gitignored — never commit it.
 */
return [
    'password_hash' => '',
    /** Optional: https://your-cdn.example.com (no trailing slash). Used for full email image URLs when set. */
    'public_base_url' => '',
    /** Optional: hex key for signed dynamic timer URLs (auto-generated by installer/setup script). */
    'timer_signing_key' => '',
];
